# このサイト全体のタイトル
site_name: okamu.ro | 岡室庄悟

# meta description（og:description・twitter:descriptionでも使用）
description: 岡室庄悟（おかむろ　しょうご）、通称おかむーのポートフォリオサイトです

# meta keywords
keywords: ["岡室庄悟","岡室","庄悟","岡村","おかむろ","しょうご","おかむろしょうご","KAYAC","カヤック","九工大","九州工業大学","P&D","かまってちゃん","kamatte","カマッテ","クッリぼっち","シンデレラ","出合い系","サービス"]

# カノニカル・og:urlなどで使われる、このサイトのURL
# （複数ページあるサイトでは、全てに同じURLを入れないように）
url: https://www.okamu.ro/

# Facebook OGP・Twitter cardsで使われる画像 フルURLで指定すること
ogp_image_url: https://www.okamu.ro/images/ogp.jpg

# Facebookアプリのapp id（入れないとWarningが出る）
facebook_app_id: 736651669859029

# Twitter cardsの管理者として登録するアカウント（※任意）
# twitter_card_owner: '@TwitterJP'

# favicon
favicon_url: /favicon.ico

# サイトをホーム画面に追加した際のアイコン画像
# webclipicon_url: http://example.com/webclipicon.png

# iOSにて、サイトをホーム画面に追加した際の、ステータスバーの挙動指定
ios_status_bar: default
